services:
  mongo.db.catalog:
    container_name: mongo.db.catalog.container
    image: mongo:8.2
    restart: always
    ports:
      - "27030:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    command: >
      bash -c "openssl rand -base64 756 > /etc/mongo-keyfile &&
      chmod 400 /etc/mongo-keyfile &&
      chown mongodb:mongodb /etc/mongo-keyfile &&
      docker-entrypoint.sh mongod --replSet rs0 --bind_ip_all --keyFile /etc/mongo-keyfile"
    healthcheck:
      test: |
        test $$(mongosh --quiet -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --eval "try { rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: 'localhost:27017' }] }).ok } catch (_) { rs.status().ok }") -eq 1
      interval: 10s
      start_period: 5s
    volumes:
      - mongo.db.catalog.volume:/data/db
  redis.db.basket:
    container_name: redis.db.basket.container
    image: redis:8.6
    restart: always
    ports:
      - "63790:6379"
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    volumes:
      - redis.db.basket.volume:/data
  mongo.db.discount:
    container_name: mongo.db.discount.container
    image: mongo:8.2
    restart: always
    ports:
      - "27031:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    command: >
      bash -c "openssl rand -base64 756 > /etc/mongo-keyfile &&
      chmod 400 /etc/mongo-keyfile &&
      chown mongodb:mongodb /etc/mongo-keyfile &&
      docker-entrypoint.sh mongod --replSet rs0 --bind_ip_all --keyFile /etc/mongo-keyfile"
    healthcheck:
      test: |
        test $$(mongosh --quiet -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --eval "try { rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: 'localhost:27017' }] }).ok } catch (_) { rs.status().ok }") -eq 1
      interval: 10s
      start_period: 5s
    volumes:
      - mongo.db.discount.volume:/data/db
  sqlserver.db.order:
    container_name: sqlserver.db.order.container
    image: mcr.microsoft.com/mssql/server:2025-latest
    restart: always
    ports:
      - "14330:1433"
    environment:
      SA_PASSWORD: ${SQLSERVER_PASSWORD}
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver.db.order.volume:/var/opt/mssql
  keycloak:
    container_name: keycloak.container
    image: quay.io/keycloak/keycloak:26.6.2
    restart: always
    ports:
      - "8080:8080"
    environment:
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HOSTNAME_STRICT: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres.db.keycloak/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    command: start
    depends_on:
      - postgres.db.keycloak
  postgres.db.keycloak:
      container_name: postgres.db.keycloak.container
      image: postgres:18.4
      restart: always
      ports:
        - "54320:5432"
      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      volumes:
        - postgres.db.keycloak.volume:/var/lib/postgresql

volumes:
  mongo.db.catalog.volume:
  redis.db.basket.volume:
  mongo.db.discount.volume:
  sqlserver.db.order.volume:
  postgres.db.keycloak.volume: